CREATE TABLE `jx_p_agreement` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '合同ID',
  `contract_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '合同名称',
  `is_master` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否是主合同，0:否，1:是 ,  2:夏校， 3：单项服务',
  `contract_number` varchar(50) COLLATE utf8_unicode_ci DEFAULT '' COMMENT '合同编号',
  `qiantu_id` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '前途合同ID',
  `customer_name` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '客户名称',
  `card` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '身份证号',
  `card_type` tinyint(3) DEFAULT NULL COMMENT '身份证类型:1身份证,2护照,3其他',
  `phone` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '手机号',
  `address` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '地址',
  `email` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '邮箱',
  `school_year` int(4) unsigned DEFAULT '0' COMMENT '入学年份',
  `country_name` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '原意向国家',
  `major_name` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '原意向专业',
  `subject_name` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '原意向科系',
  `degree` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '原意向学位',
  `file_time` int(11) unsigned DEFAULT '0' COMMENT '合同归档时间',
  `file_money` int(11) unsigned DEFAULT '0' COMMENT '合同归档金额',
  `service_charge` int(11) unsigned DEFAULT '0' COMMENT '基本服务费',
  `money` decimal(11,2) unsigned DEFAULT '0.00' COMMENT '合同的签约金额',
  `campuses_id` int(11) unsigned DEFAULT '0' COMMENT '所属校区id',
  `edu_email` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '教务老师邮箱',
  `document_email` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '文书老师邮箱',
  `adviser_email` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '顾问老师邮箱',
  `adviser_branch_id` int(10) NOT NULL DEFAULT '0' COMMENT '顾问老师所属分公司',
  `start_adviser_email` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '前期顾问邮箱',
  `teaching_email` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '授课老师邮箱',
  `create_time` int(11) DEFAULT '0' COMMENT '合同创建时间',
  `status` int(4) unsigned DEFAULT '0' COMMENT '合同状态',
  `pay_branch_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT '' COMMENT '学生交付地(保留不能被匹配的特殊地)',
  `status_name` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '合同状态名称',
  `class_hour` varchar(50) COLLATE utf8_unicode_ci DEFAULT '0' COMMENT '必修课总时',
  `product_cate_id` int(10) unsigned DEFAULT '0' COMMENT '产品大类ID',
  `service_status` tinyint(1) unsigned DEFAULT '0' COMMENT '服务状态',
  `budget` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '总预算',
  `ag_give_hour` decimal(10,2) unsigned DEFAULT '0.00' COMMENT '合同赠送课时',
  `ag_choose_hour` decimal(10,2) unsigned DEFAULT '0.00' COMMENT '合同选修课课时',
  `ag_project` decimal(10,2) unsigned DEFAULT '0.00' COMMENT '合同项目数',
  `ag_type` decimal(10,2) unsigned DEFAULT '0.00' COMMENT '合同排版数',
  `be_class_hour` decimal(10,2) unsigned DEFAULT '0.00' COMMENT '已完成必修课课时',
  `be_give_hour` decimal(10,2) unsigned DEFAULT '0.00' COMMENT '已完成赠送课时',
  `be_choose_hour` decimal(10,2) unsigned DEFAULT '0.00' COMMENT '已完成选修课课时',
  `be_project` decimal(10,2) unsigned DEFAULT '0.00' COMMENT '已完成项目数',
  `be_project_modify` decimal(10,2) DEFAULT '0.00' COMMENT '已完成项目数变动值',
  `be_type` decimal(10,2) unsigned DEFAULT '0.00' COMMENT '已完成排版数',
  `be_type_modify` decimal(10,2) DEFAULT '0.00' COMMENT '已完成排版数变动值',
  `biz_time` int(10) unsigned DEFAULT NULL COMMENT '签约日期',
  `type` tinyint(1) unsigned DEFAULT '0' COMMENT '添加类型：0为erp推送1为自己添加',
  `course_start_time` int(10) unsigned DEFAULT NULL COMMENT '课程开始时间',
  `course_end_time` int(10) unsigned DEFAULT NULL COMMENT '课程结束时间',
  `out_branch_id` int(10) unsigned DEFAULT '0' COMMENT '转出校区',
  `must_class_end_time` int(11) DEFAULT '0' COMMENT '必修课结束时间',
  `type_end_time` int(11) DEFAULT '0' COMMENT '排版结束时间',
  `created_at` int(11) unsigned DEFAULT NULL COMMENT '创建时间',
  `updated_at` int(11) unsigned DEFAULT NULL COMMENT '更新时间',
  `class_add_hours` smallint(6) DEFAULT NULL COMMENT '补充协议增加课时数',
  `class_core_hours` smallint(6) DEFAULT NULL COMMENT '核心课时数',
  `value_add_hours` smallint(6) DEFAULT NULL COMMENT '增值课时数',
  `cf_gift` smallint(6) DEFAULT NULL COMMENT '赠送课时数',
  `cf_lesson_times` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '赠送课程',
  `cf_content` text COLLATE utf8_unicode_ci COMMENT '附加协议内容说明',
  `has_add_contract` tinyint(3) DEFAULT '0' COMMENT '是否有附加协议',
  `add_contract_status` tinyint(3) DEFAULT '0' COMMENT '附加协议是否已由相关负责人审核通过',
  `pay_branch_id` tinyint(3) NOT NULL DEFAULT '0' COMMENT '合同交付地对应校区id',
  `fid` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '合同fid',
  `total_end_time` int(11) DEFAULT '0' COMMENT '整体结课日期',
  `typeset_time` int(11) DEFAULT NULL COMMENT '排版结束日期',
  `is_recommend` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '是否和学生推荐授课老师:0否1是',
  `is_assessed` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '报名之前是否进行过作品评估:0否1是',
  `is_listened` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '报名之前是否进行过试听课:0否1是',
  `is_assisted` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '报名之前是否进行过辅助咨询:0否1是',
  `goal_school` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '目标院校',
  `special_comment` text COLLATE utf8_unicode_ci COMMENT '合同内容中需要向教务特别说明的内容',
  `full_pay` tinyint(2) NOT NULL DEFAULT '0' COMMENT '该学生是否已经付全款:0否1是',
  `payed_class_hour` mediumint(8) NOT NULL DEFAULT '0' COMMENT '目前已付款项对应需上课时数',
  `discount_content` text COLLATE utf8_unicode_ci COMMENT '优惠协议-给予内容',
  `erp_have_class` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT 'erp合同必修课时',
  `erp_give_class` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT 'erp合同赠送课时',
  `erp_chose_class` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT 'erp合同选修课时',
  `erp_project_count` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT 'erp合同项目数',
  `erp_type_count` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT 'erp合同排版数',
  `must_course_sum` text COLLATE utf8_unicode_ci COMMENT '必修课计算结果json',
  `give_course_sum` text COLLATE utf8_unicode_ci COMMENT '选修课计算结果json',
  `is_count` tinyint(3) DEFAULT '0' COMMENT '是否计算变更和新增',
  `related_product` tinyint(3) DEFAULT '0' COMMENT '合同是否关联过产品课程和服务',
  `school_edit_num` smallint(6) DEFAULT '0' COMMENT '院校改版个数',
  `customer_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '客户ID',
  `previous_master_id` int(11) NOT NULL DEFAULT '0' COMMENT '上一个主合同的id',
  PRIMARY KEY (`id`),
  KEY `card` (`card`),
  KEY `idx_customer_id` (`customer_id`),
  KEY `idx_ct_number` (`contract_name`) USING BTREE,
  KEY `idx_agreement_status_service` (`status`,`service_status`,`customer_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='合同表';
