CREATE TABLE `jx_p_customer` (
  `customer_id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `client_id` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'erp客户ID',
  `open_id` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'openid',
  `nick_name` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '微信昵称',
  `head_img` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '微信头像',
  `name` varchar(50) CHARACTER SET utf8 DEFAULT '' COMMENT '客户姓名',
  `old_name` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '客户姓名',
  `mobile_phone` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '客户手机号',
  `nps_phone` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT '学生NPS电话',
  `parent_phone` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '家长联系电话',
  `contract_phone` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '合同手机号',
  `card_type` tinyint(1) DEFAULT '1' COMMENT '证件号类型1：身份证 2为护照',
  `card` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '身份证号',
  `passport` varchar(15) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '护照号码',
  `birthday` int(10) unsigned DEFAULT NULL COMMENT '学生生日',
  `belong_branch_id` int(11) DEFAULT NULL COMMENT '所属校区ID',
  `campuses_id` int(11) DEFAULT NULL COMMENT '所属校区id(作废)',
  `edu_email` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT '' COMMENT '教务老师邮箱',
  `edu_branch_id` int(11) DEFAULT NULL COMMENT '教务地区',
  `first_tutor_email` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT '' COMMENT '主导师',
  `second_tutor_email` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT '' COMMENT '辅导师',
  `selection_email` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT '' COMMENT '选校老师',
  `document_email` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT '' COMMENT '文书老师邮箱',
  `document_director_email` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT '文书主管邮箱',
  `application_email` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT '申请老师邮箱',
  `adviser_email` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT '' COMMENT '顾问老师邮箱',
  `second_adviser_email` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT '' COMMENT '辅助顾问',
  `course_email` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '选课老师邮箱',
  `teaching_email` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '授课老师邮箱',
  `email` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '学生邮箱',
  `graduate_school` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '目前就读院校/毕业学校',
  `graduate_major` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '毕业专业',
  `is_sign` tinyint(2) DEFAULT '10' COMMENT '是否签约合同 10是 20不是',
  `status` tinyint(2) DEFAULT '11' COMMENT '状态 11:正常 88:删除 99:禁止登陆',
  `is_login` tinyint(1) unsigned DEFAULT '0' COMMENT '是否登录过：0为否1为是',
  `last_login_ip` char(15) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '最后登录IP',
  `last_login_time` int(11) DEFAULT NULL COMMENT '最后登录时间',
  `biz_time` int(10) unsigned DEFAULT NULL COMMENT '入学时间',
  `oper_id` int(10) unsigned DEFAULT NULL COMMENT '操作人ID',
  `sex` tinyint(1) unsigned DEFAULT '1' COMMENT '性别：1为男2为女',
  `school_name` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '目前就读学校',
  `course_set_id` int(10) unsigned DEFAULT '0' COMMENT '课程设置ID',
  `home_address` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '家庭住址',
  `summer_school_id` int(10) unsigned DEFAULT '0' COMMENT '夏校ID',
  `lang_score` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '语言成绩',
  `ielts_id` int(10) unsigned DEFAULT '0' COMMENT '雅思ID',
  `gpa_id` int(10) unsigned DEFAULT '0' COMMENT '已废除',
  `jlpt` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'jlpt',
  `toefl` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '托福',
  `sat` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'sat',
  `eju` char(6) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT '日本EJU成绩',
  `add_type` tinyint(1) unsigned DEFAULT '1' COMMENT '添加类型：1为接口2位手动添加',
  `other_lang` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '其他语言',
  `server_porg` tinyint(1) unsigned DEFAULT '0' COMMENT '1为服务中2为已结课3为已退费4为退费中',
  `many_country` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '多邻国',
  `edu_area` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '教务地区',
  `is_change_school` tinyint(1) DEFAULT '2' COMMENT '是否转校区，1：是 2：否',
  `style_end_time` int(11) DEFAULT NULL COMMENT '整体排版服务结束日',
  `is_better` tinyint(1) DEFAULT '2' COMMENT '海外教授项目课，1：有 2：无',
  `master_class` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '大师课名称',
  `is_better_coach` tinyint(1) DEFAULT '2' COMMENT '海外教授项目辅导，1：有 2：无',
  `is_better_task` tinyint(1) DEFAULT '2' COMMENT '海外教授作业批改-2次，1：有 2：无',
  `is_better_review` tinyint(1) DEFAULT '2' COMMENT '海外名校终审核，1：有 2：无',
  `is_document` tinyint(1) DEFAULT '2' COMMENT '文书服务 : 1 有 ,2 无, 3 文书在前途 4 文书在高校, 5 文书在其他中介',
  `is_edition` tinyint(1) unsigned DEFAULT '2' COMMENT '排版服务 1 有 2 无',
  `remarks` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT '' COMMENT '备注',
  `created_at` int(11) DEFAULT NULL COMMENT '创建时间',
  `updated_at` int(11) DEFAULT NULL COMMENT '修改时间',
  `inter_course_subjects_and_grades` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT '' COMMENT '国际课程可修科目及成绩',
  `gpa` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT '' COMMENT 'GPA',
  `phonetic_name` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT '姓名拼音(同护照一致)',
  `english_name` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT '英文名',
  `student_number` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '学号',
  `customer_service_phone` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT '客服信息电话',
  `service_contact_date` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '服务对接日期',
  PRIMARY KEY (`customer_id`),
  KEY `card` (`card`),
  KEY `belong_branch_id` (`belong_branch_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='客户表';
